spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderplatform
    username: orderplatform
    password: orderplatform
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    open-in-view: false

jwt:
  secret: dGhpcyBpcyBhIHZlcnkgc2VjdXJlIGtleSBmb3Igb3JkZXIgcGxhdGZvcm0gand0IHNpZ25pbmc=
  expiration: 3600000
