spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/payment_db
    username: orderplatform
    password: orderplatform
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-group

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    open-in-view: false

internal-token:
  secret: b3JkZXJwbGF0Zm9ybS1pbnRlcm5hbC10b2tlbi1zZWNyZXQta2V5LWZvci1obWFjLXNoYTI1Ng==
