spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/product_db
    username: orderplatform
    password: orderplatform
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: product-group

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    open-in-view: false
